version: "3"
services:
  mongo-node-1:
    container_name: mongo-node-1
    restart: always
    build: .
    ports:
      - "30001:27017"
    depends_on:
      - mongo-node-2
    networks:
      - mongo-cluster
    volumes:
      - ./data/node-1:/data/db
  mongo-node-2:
    container_name: mongo-node-2
    restart: always
    image: mongo
    volumes:
      - ./data/node-2:/data/db
    ports:
      - "30002:27017"
    depends_on:
      - mongo-node-3
    networks:
      - mongo-cluster
    command: --replSet mongo-cluster
  mongo-node-3:
    container_name: mongo-node-3
    restart: always
    image: mongo
    ports:
      - "30003:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./data/node-3:/data/db
    command: --replSet mongo-cluster
networks:
  mongo-cluster:
